# Generated by Django 3.0.3 on 2020-05-19 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='data_cadastro',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='listaequipamento',
            name='data_inclusao',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='quadroacessorio',
            name='quantidade',
            field=models.IntegerField(default=0, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='quadroequipamentos',
            name='quantidade',
            field=models.IntegerField(default=0, verbose_name='Quantidade'),
        ),
    ]
