# Generated by Django 3.0.3 on 2020-05-21 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0011_auto_20200518_1948'),
        ('locacao', '0002_auto_20200519_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empresa.Cliente'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='observacoes',
            field=models.CharField(max_length=300, verbose_name='Obs. Geral'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='obsnota',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Obs. Nota'),
        ),
    ]
