# Generated by Django 3.0.3 on 2020-05-25 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locacao', '0003_auto_20200521_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quadroequipamentos',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='quadroequipamentos',
            name='data_desativado',
        ),
    ]
