# Generated by Django 3.0.3 on 2020-05-27 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0011_auto_20200518_1948'),
        ('locacao', '0004_auto_20200525_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='listaequipamento',
            name='empresa',
            field=models.ForeignKey(default='11771285000180', on_delete=django.db.models.deletion.PROTECT, to='empresa.Empresa'),
            preserve_default=False,
        ),
    ]
