# Generated by Django 3.0.3 on 2020-06-04 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locacao', '0005_listaequipamento_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='observacoes',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Obs. Geral'),
        ),
    ]
