# Generated by Django 3.0.3 on 2020-05-13 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0008_auto_20200430_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEquipamento',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False, verbose_name='Código')),
                ('marca', models.CharField(blank=True, default='Padrão', max_length=100, null=True, verbose_name='Marca')),
                ('modelo', models.CharField(blank=True, default='Padrão', max_length=100, null=True, verbose_name='Modelo')),
                ('preco', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Preço')),
                ('empresa', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='empresa.Empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('serial', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Serial')),
                ('status', models.CharField(choices=[('1', 'DISPONIVEL'), ('2', 'LOCADO'), ('3', 'MANUTENCAO'), ('4', 'PERDIDO')], default='1', max_length=2, verbose_name='Status')),
                ('empresa', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='empresa.Empresa')),
                ('tipo', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='inventario.TipoEquipamento')),
            ],
        ),
        migrations.CreateModel(
            name='Acessorio',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False, verbose_name='Código')),
                ('descricao', models.CharField(blank=True, default='Padrão', max_length=100, null=True, verbose_name='Descrição')),
                ('preco', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Preço')),
                ('quantidade', models.CharField(blank=True, default='1', max_length=100, null=True, verbose_name='Quantidade')),
                ('empresa', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='empresa.Empresa')),
            ],
        ),
    ]
