# Generated by Django 3.0.3 on 2020-05-13 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acessorio',
            name='ativo',
            field=models.BooleanField(blank=True, default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='acessorio',
            name='data_desativado',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='ativo',
            field=models.BooleanField(blank=True, default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='data_desativado',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
