# Generated by Django 3.0.3 on 2020-05-18 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_auto_20200513_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoequipamento',
            name='ativo',
            field=models.BooleanField(blank=True, default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='tipoequipamento',
            name='data_desativado',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
