# Generated by Django 3.0.3 on 2020-05-19 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_auto_20200518_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoequipamento',
            name='quantidade',
            field=models.IntegerField(default=0, max_length=100, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='acessorio',
            name='quantidade',
            field=models.IntegerField(default=0, max_length=100, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='status',
            field=models.CharField(choices=[('1', 'DISPONIVEL'), ('2', 'LOCADO'), ('3', 'MANUTENCAO')], default='1', max_length=2, verbose_name='Status'),
        ),
    ]
