# Generated by Django 3.0.3 on 2020-05-19 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_auto_20200519_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acessorio',
            name='quantidade',
            field=models.IntegerField(default=0, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='tipoequipamento',
            name='quantidade',
            field=models.IntegerField(default=0, verbose_name='Quantidade'),
        ),
    ]
