# Generated by Django 3.0.3 on 2020-07-22 22:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0014_auto_20200708_1924'),
        ('inventario', '0009_auto_20200604_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicoequipamento',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='empresa.Usuario'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='status',
            field=models.CharField(choices=[('1', 'DISPONIVEL'), ('2', 'LOCADO'), ('3', 'MANUTENCAO')], default='1', max_length=2, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='historicoequipamento',
            name='data_evento',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 22, 19, 50, 37, 396981)),
        ),
        migrations.AlterField(
            model_name='historicoequipamento',
            name='descricao',
            field=models.CharField(default='Padrão', max_length=100, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='historicoequipamento',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='empresa.Empresa'),
        ),
        migrations.AlterField(
            model_name='historicoequipamento',
            name='equipamento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.Equipamento'),
        ),
    ]
