# Generated by Django 3.0.3 on 2020-07-22 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_auto_20200722_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicoequipamento',
            name='data_evento',
            field=models.DateTimeField(default='2020-01-01'),
        ),
    ]
