# Generated by Django 3.0.3 on 2020-07-22 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0014_auto_20200708_1924'),
        ('inventario', '0011_auto_20200722_1952'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipamentoPerdido',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False, verbose_name='Código')),
                ('descricao', models.CharField(default='Padrão', max_length=100, verbose_name='Descrição')),
                ('ultimo_contrato', models.CharField(default='00', max_length=100, verbose_name='Último Contrato')),
                ('data_evento', models.DateTimeField(default='2020-01-01')),
                ('empresa', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='empresa.Empresa')),
                ('equipamento', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.Equipamento')),
            ],
        ),
    ]
