# Generated by Django 3.0.3 on 2020-07-24 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0014_auto_20200708_1924'),
        ('inventario', '0012_equipamentoperdido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamentoperdido',
            name='descricao',
            field=models.TextField(default='Padrão', max_length=100, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='equipamentoperdido',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='empresa.Empresa'),
        ),
        migrations.AlterField(
            model_name='equipamentoperdido',
            name='equipamento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='inventario.Equipamento'),
        ),
    ]
