# Generated by Django 3.0.3 on 2020-07-28 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0013_auto_20200724_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamentoperdido',
            name='ativo',
            field=models.BooleanField(blank=True, default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='equipamentoperdido',
            name='data_desativado',
            field=models.DateTimeField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='status',
            field=models.CharField(choices=[('1', 'DISPONIVEL'), ('2', 'LOCADO'), ('3', 'MANUTENCAO'), ('4', 'PERDIDO')], default='1', max_length=2, verbose_name='Status'),
        ),
    ]
