# Generated by Django 3.0.3 on 2020-07-28 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0014_auto_20200728_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamentoperdido',
            name='data_desativado',
            field=models.DateTimeField(blank=True, default='2020-01-01', null=True),
        ),
    ]
