# Generated by Django 3.0.3 on 2020-07-28 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0015_auto_20200728_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipamentoperdido',
            name='data_desativado',
        ),
    ]
