# Generated by Django 3.0.3 on 2020-07-28 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0016_remove_equipamentoperdido_data_desativado'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamentoperdido',
            name='data_desativado',
            field=models.DateTimeField(blank=True, default='2020-01-01', null=True),
        ),
    ]
