# Generated by Django 3.0.3 on 2020-06-27 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0011_auto_20200518_1948'),
        ('locacao', '0006_auto_20200604_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaCobranca',
            fields=[
                ('numnota', models.IntegerField(primary_key=True, serialize=False, verbose_name='Numero Nota')),
                ('datafechamento', models.DateField(blank=True, null=True, verbose_name='Data Fechamento')),
                ('nomecliente', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome Cliente')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Valor')),
                ('pedido', models.CharField(blank=True, default='N/A', max_length=100, null=True, verbose_name='Pedido')),
                ('obsnota', models.CharField(blank=True, default='N/A', max_length=300, null=True, verbose_name='Obs Nota')),
                ('cancelada', models.BooleanField(blank=True, default=False, verbose_name='Cancelada')),
                ('data_inclusao', models.DateTimeField()),
                ('data_cancelada', models.DateTimeField(blank=True, null=True)),
                ('cnpjcliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='empresa.Cliente')),
                ('contrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='locacao.Contrato')),
                ('empresa', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='empresa.Empresa')),
            ],
        ),
    ]
