# Generated by Django 3.0.3 on 2020-07-07 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notacobranca',
            name='nomecliente',
        ),
    ]
