# Generated by Django 3.0.3 on 2020-07-08 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locacao', '0006_auto_20200604_1233'),
        ('faturamento', '0003_auto_20200707_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notacobranca',
            name='contrato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='locacao.Contrato'),
        ),
    ]
