# Generated by Django 3.0.2 on 2020-01-21 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('cnpjCpf', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='CNPJ / CPF')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('razaoSocial', models.CharField(max_length=100, verbose_name='Razão Social')),
                ('responsavel', models.CharField(blank=True, max_length=100, null=True, verbose_name='Rensponsável')),
                ('inscestadual', models.CharField(default='00000000', max_length=100, verbose_name='Inscricao Estadual')),
                ('inscmunicipal', models.CharField(default='00000000', max_length=100, verbose_name='Inscricao Municipal')),
                ('telefone', models.CharField(max_length=100, verbose_name='Telefone')),
                ('endRua', models.CharField(default='01', max_length=100, verbose_name='Rua')),
                ('endComplemento', models.CharField(default='01', max_length=100, verbose_name='Complemento')),
                ('endCidade', models.CharField(default='01', max_length=100, verbose_name='Cidade')),
                ('endUF', models.CharField(default='RS', max_length=100, verbose_name='UF')),
                ('endCEP', models.CharField(default='00000000', max_length=10, verbose_name='CEP')),
                ('email', models.CharField(max_length=100, verbose_name='E-mail')),
                ('senhaWeb', models.CharField(max_length=100, verbose_name='Senha')),
                ('site', models.CharField(default='não cadastrado', max_length=100, verbose_name='Site')),
                ('nivel', models.CharField(default='Matriz', max_length=100, verbose_name='Nivel')),
            ],
        ),
    ]
