# Generated by Django 3.0.3 on 2020-04-22 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='empresa',
        ),
    ]
