# Generated by Django 3.0.3 on 2020-04-29 11:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0006_auto_20200427_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cnpjCpf', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='CNPJ / CPF')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('razaoSocial', models.CharField(max_length=100, verbose_name='Razão Social')),
                ('responsavel', models.CharField(blank=True, max_length=100, null=True, verbose_name='Rensponsável')),
                ('inscestadual', models.CharField(blank=True, max_length=100, null=True, verbose_name='Inscricao Estadual')),
                ('inscmunicipal', models.CharField(blank=True, max_length=100, null=True, verbose_name='Inscricao Municipal')),
                ('telefone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telefone')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='E-mail')),
                ('site', models.CharField(blank=True, max_length=100, null=True, verbose_name='Site')),
                ('endRua', models.CharField(blank=True, max_length=100, null=True, verbose_name='Rua')),
                ('endComplemento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento')),
                ('endCidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade')),
                ('endUF', models.CharField(blank=True, max_length=100, null=True, verbose_name='UF')),
                ('endCEP', models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP')),
                ('senhaWeb', models.CharField(blank=True, max_length=100, null=True, verbose_name='Senha')),
                ('tipo', models.CharField(choices=[('01', 'Juridica'), ('02', 'Fisica')], default='01', max_length=2, verbose_name='Tipo')),
                ('dataCriacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('restricao', models.BooleanField(blank=True, default=True, verbose_name='Restricao')),
                ('textorestricao', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Observacao Restricao')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empresa.Empresa')),
            ],
        ),
    ]
