# Generated by Django 3.0.3 on 2020-05-13 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0008_auto_20200430_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='ativo',
            field=models.BooleanField(blank=True, default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ativo',
            field=models.BooleanField(blank=True, default=True, verbose_name='Ativo'),
        ),
    ]
