# Generated by Django 3.0.3 on 2020-05-13 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0009_auto_20200513_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='data_desativado',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='data_desativado',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
