# Generated by Django 3.0.3 on 2020-05-18 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0010_auto_20200513_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='restricao',
            field=models.BooleanField(blank=True, default=False, verbose_name='Restricao'),
        ),
    ]
